// Данные аниме (ваши любимые) с картинками
const animeData = [
  {
    id: 1,
    title: "Гачиакута",
    title_en: "Gachiakuta",
    title_de: "Gachiakuta",
    title_ja: "ガチアクタ",
    title_zh: "ガチアクタ",
    image: "https://v12.vost.pw/uploads/posts/2025-06/1750584642_1.jpg?v2",
    description: "История о Рудже, жителе трущоб, который попадает в таинственный мир Гачиакуты, где сталкивается с демонами и древними секретами. Он получает могущественные способности и начинает свое путешествие по раскрытию правды о своем прошлом.",
    description_en: "The story of Rudge, a slum dweller who enters the mysterious world of Gachiakuta, where he encounters demons and ancient secrets. He gains powerful abilities and begins his journey to uncover the truth about his past.",
    description_de: "Die Geschichte von Rudge, einem Slumbewohner, der in die mysteriöse Welt von Gachiakuta gelangt, wo er auf Dämonen und uralte Geheimnisse stößt. Er erhält mächtige Fähigkeiten und beginnt seine Reise, die Wahrheit über seine Vergangenheit aufzudecken.",
    description_ja: "スラム街の住人であるラジが、ガチアクタという謎めいた世界に入り、悪魔や古代の秘密に遭遇する物語。彼は強力な能力を獲得し、自分の過去の真実を解明するための旅を始める。",
    description_zh: "讲述贫民窟居民鲁吉进入神秘的ガチアクタ世界，遭遇恶魔和古老秘密的故事。他获得了强大的能力，并开始揭开自己过去真相的旅程。",
    genres: ["Экшен", "Фэнтези", "Приключения", "Драма"],
    genres_en: ["Action", "Fantasy", "Adventure", "Drama"],
    genres_de: ["Action", "Fantasy", "Abenteuer", "Drama"],
    genres_ja: ["アクション", "ファンタジー", "アドベンチャー", "ドラマ"],
    genres_zh: ["动作", "奇幻", "冒险", "剧情"],
    format: "TV Сериал",
    format_en: "TV Series",
    format_de: "TV-Serie",
    format_ja: "TVシリーズ",
    format_zh: "电视系列",
    episodes: 24,
    averageScore: 84
  },
  {
    id: 2,
    title: "Хроники людей и демонов",
    title_en: "Chronicles of Humans and Demons",
    title_de: "Chroniken von Menschen und Dämonen",
    title_ja: "人間と悪魔の年代記",
    title_zh: "人类与恶魔编年史",
    image: "https://v12.vost.pw/uploads/posts/2024-06/1717509032_1.jpg?v2",
    description: "В мире, где люди сражаются с демонами за выживание, юный воин присоединяется к элите охотников на демонов. Сюжет исследует моральные дилеммы и сложные отношения между двумя расами.",
    description_en: "In a world where humans fight demons for survival, a young warrior joins the elite demon hunters. The plot explores moral dilemmas and complex relationships between the two races.",
    description_de: "In einer Welt, in der Menschen ums Überleben gegen Dämonen kämpfen, schließt sich ein junger Krieger den Elite-Dämonenjägern an. Die Handlung erforscht moralische Dilemmata und komplexe Beziehungen zwischen den beiden Rassen.",
    description_ja: "人間が悪魔と生存をかけて戦う世界で、若き戦士がエリートの悪魔狩りに加わる。プロットは、2つの種族間の道徳的ジレンマと複雑な関係を探求する。",
    description_zh: "在一个人类为生存而与恶魔战斗的世界里，一位年轻战士加入了精英恶魔猎人队伍。剧情探讨了两个种族之间的道德困境和复杂关系。",
    genres: ["Экшен", "Фэнтези", "Драма", "Сверхъестественное"],
    genres_en: ["Action", "Fantasy", "Drama", "Supernatural"],
    genres_de: ["Action", "Fantasy", "Drama", "Übernatürliches"],
    genres_ja: ["アクション", "ファンタジー", "ドラマ", "超自然"],
    genres_zh: ["动作", "奇幻", "剧情", "超自然"],
    format: "TV Сериал",
    format_en: "TV Series",
    format_de: "TV-Serie",
    format_ja: "TVシリーズ",
    format_zh: "电视系列",
    episodes: 24,
    averageScore: 82
  },
  {
    id: 3,
    title: "Кайдзю №8",
    title_en: "Kaiju No. 8",
    title_de: "Kaiju Nr. 8",
    title_ja: "怪獣8号",
    title_zh: "怪兽8号",
    image: "https://v12.vost.pw/uploads/posts/2025-06/1750245339_3.jpg?v2",
    description: "В Японии, регулярно подвергающейся атакам кайдзю, Кафка Хибино работает в команде по уборке останков монстров. После неожиданного события он сам становится кайдзю №8 и должен скрывать свою природу, сражаясь с другими монстрами.",
    description_en: "In Japan, regularly attacked by kaiju, Kafka Hibino works in a monster cleanup crew. After an unexpected event, he himself becomes Kaiju No. 8 and must hide his nature while fighting other monsters.",
    description_de: "In Japan, das regelmäßig von Kaiju angegriffen wird, arbeitet Kafka Hibino in einem Monster-Beseitigungstrupp. Nach einem unerwarteten Ereignis wird er selbst zu Kaiju Nr. 8 und muss seine Natur verbergen, während er andere Monster bekämpft.",
    description_ja: "怪獣の攻撃が定期的にある日本で、カフカ・ヒビノは怪獣の残骸処理チームで働いている。予期せぬ出来事の後、彼自身が怪獣8号になり、他の怪獣と戦いながら自分の本性を隠さなければならない。",
    description_zh: "在经常遭受怪兽攻击的日本，卡夫卡·日比野在怪兽清理队工作。一次意外事件后，他自己变成了怪兽8号，必须在与其他怪物战斗的同时隐藏自己的本性。",
    genres: ["Экшен", "Комедия", "Сёнэн", "Суперсила"],
    genres_en: ["Action", "Comedy", "Shonen", "Super Power"],
    genres_de: ["Action", "Komödie", "Shonen", "Superkraft"],
    genres_ja: ["アクション", "コメディ", "少年", "超能力"],
    genres_zh: ["动作", "喜剧", "少年", "超能力"],
    format: "TV Сериал",
    format_en: "TV Series",
    format_de: "TV-Serie",
    format_ja: "TVシリーズ",
    format_zh: "电视系列",
    episodes: 23,
    averageScore: 86
  },
  {
    id: 4,
    title: "Песнь ночных сов",
    title_en: "Song of Night Owls",
    title_de: "Lied der Nachteulen",
    title_ja: "夜ふくろうの歌",
    title_zh: "夜莺之歌",
    image: "https://v12.vost.pw/uploads/posts/2025-06/1750322019_1.jpg?v2",
    description: "В подземном мире, населенном вампирами и другими ночными существами, группа охотников пытается сохранить хрупкое равновесие между мирами. Главный герой обладает уникальной способностью видеть истинную сущность существ.",
    description_en: "In an underground world inhabited by vampires and other night creatures, a group of hunters tries to maintain a fragile balance between worlds. The main character has the unique ability to see the true essence of beings.",
    description_de: "In einer von Vampiren und anderen Nachtwesen bewohnten Unterwelt versucht eine Gruppe von Jägern, ein zerbrechliches Gleichgewicht zwischen den Welten aufrechtzuerhalten. Der Hauptcharakter hat die einzigartige Fähigkeit, das wahre Wesen der Kreaturen zu sehen.",
    description_ja: "吸血鬼や他の夜の生き物が住む地下世界で、ハンターのグループが世界間の脆い均衡を維持しようとする。主人公は生き物の真の本質を見る独特の能力を持っている。",
    description_zh: "在一个居住着吸血鬼和其他夜行生物的地下世界，一群猎人试图维持世界之间脆弱的平衡。主角拥有看到生物真实本质的独特能力。",
    genres: ["Фэнтези", "Мистика", "Драма", "Приключения"],
    genres_en: ["Fantasy", "Mystery", "Drama", "Adventure"],
    genres_de: ["Fantasy", "Mystery", "Drama", "Abenteuer"],
    genres_ja: ["ファンタジー", "ミステリー", "ドラマ", "アドベンチャー"],
    genres_zh: ["奇幻", "悬疑", "剧情", "冒险"],
    format: "TV Сериал",
    format_en: "TV Series",
    format_de: "TV-Serie",
    format_ja: "TVシリーズ",
    format_zh: "电视系列",
    episodes: 25,
    averageScore: 83
  },
  {
    id: 5,
    title: "Повелитель тайн: Клоун",
    title_en: "Lord of Mysteries: Clown",
    title_de: "Herr der Geheimnisse: Clown",
    title_ja: "秘密の主: 道化師",
    title_zh: "诡秘之主：小丑",
    image: "https://v12.vost.pw/uploads/posts/2025-06/1751103460_1.png?v2",
    description: "В мире, где магия скрыта от обычных людей, главный герой случайно обнаруживает, что является носителем древней силы Повелителя Тайн. Чтобы защитить близких, он вынужден балансировать между обычной жизнью и миром магических интриг.",
    description_en: "In a world where magic is hidden from ordinary people, the main character accidentally discovers that he is the bearer of the ancient power of the Lord of Mysteries. To protect his loved ones, he is forced to balance between ordinary life and the world of magical intrigue.",
    description_de: "In einer Welt, in der Magie vor gewöhnlichen Menschen verborgen ist, entdeckt der Hauptcharakter versehentlich, dass er der Träger der uralten Kraft des Herrn der Geheimnisse ist. Um seine Lieben zu schützen, muss er zwischen dem gewöhnlichen Leben und der Welt der magischen Intrigen balancieren.",
    description_ja: "魔法が一般人から隠されている世界で、主人公は偶然、秘密の主の古代の力の担い手であることを発見する。愛する人を守るために、彼は普通の生活と魔法の陰謀の世界の間でバランスを取らなければならない。",
    description_zh: "在一个魔法对普通人隐藏的世界里，主角意外发现自己承载着诡秘之主的古老力量。为了保护所爱之人，他不得不在普通生活和魔法阴谋世界之间取得平衡。",
    genres: ["Мистика", "Драма", "Фэнтези", "Приключения"],
    genres_en: ["Mystery", "Drama", "Fantasy", "Adventure"],
    genres_de: ["Mystery", "Drama", "Fantasy", "Abenteuer"],
    genres_ja: ["ミステリー", "ドラマ", "ファンタジー", "アドベンチャー"],
    genres_zh: ["悬疑", "剧情", "奇幻", "冒险"],
    format: "TV Сериал",
    format_en: "TV Series",
    format_de: "TV-Serie",
    format_ja: "TVシリーズ",
    format_zh: "电视系列",
    episodes: 13,
    averageScore: 81
  },
  {
    id: 6,
    title: "Поднятие уровня в одиночку",
    title_en: "Solo Leveling",
    title_de: "Solo Leveling",
    title_ja: "俺だけレベルアップ",
    title_zh: "我独自升级",
    image: "https://v12.vost.pw/uploads/posts/2024-12/1733928184_1.jpg?v2",
    description: "В мире, где охотники сражаются с монстрами из врат, Сон Джин-У считается самым слабым охонтником. После попадания в смертельную ловушку он получает уникальную систему, позволяющую расти в силе, и начинает свое восхождение к вершине.",
    description_en: "In a world where hunters fight monsters from gates, Sung Jin-Woo is considered the weakest hunter. After falling into a deadly trap, he gains a unique system that allows him to grow in strength and begins his ascent to the top.",
    description_de: "In einer Welt, in der Jäger Monster aus Toren bekämpfen, gilt Sung Jin-Woo als der schwächste Jäger. Nachdem er in eine tödliche Falle gerät, erhält er ein einzigartiges System, das es ihm ermöglicht, an Stärke zu wachsen, und beginnt seinen Aufstieg an die Spitze.",
    description_ja: "門から現れるモンスターと戦うハンターたちの世界で、ソン・ジヌは最弱のハンターと見なされている。死の罠にかかった後、彼は力を成長させる独自のシステムを獲得し、頂点への上昇を始める。",
    description_zh: "在一个猎人对抗来自门的怪物的世界里，成镇宇被认为是最弱的猎人。陷入致命陷阱后，他获得了一个允许他成长力量的独特系统，并开始向顶峰攀登。",
    genres: ["Экшен", "Фэнтези", "Приключения", "Игра"],
    genres_en: ["Action", "Fantasy", "Adventure", "Game"],
    genres_de: ["Action", "Fantasy", "Abenteuer", "Spiel"],
    genres_ja: ["アクション", "ファンタジー", "アドベンチャー", "ゲーム"],
    genres_zh: ["动作", "奇幻", "冒险", "游戏"],
    format: "TV Сериал",
    format_en: "TV Series",
    format_de: "TV-Serie",
    format_ja: "TVシリーズ",
    format_zh: "电视系列",
    episodes: 25,
    averageScore: 88
  },
  {
    id: 7,
    title: "Арифурэта: Сильнейший ремесленник в мире",
    title_en: "Arifureta: The World's Strongest Artisan",
    title_de: "Arifureta: Der stärkste Handwerker der Welt",
    title_ja: "ありふれた世界最強の職人",
    title_zh: "平凡职业造就世界最强工匠",
    image: "https://v12.vost.pw/uploads/posts/2024-12/1734365931_1.jpg?v2",
    description: "Хадзиме Нагамото и его одноклассники попадают в фэнтезийный мир, где все получают уникальные способности. Хадзиме получает, казалось бы, бесполезную профессию ремесленника, но использует свои знания для создания невероятных технологий и оружия.",
    description_en: "Hajime Nagamoto and his classmates are transported to a fantasy world where everyone receives unique abilities. Hajime gets what seems to be a useless profession as an artisan, but uses his knowledge to create incredible technologies and weapons.",
    description_de: "Hajime Nagamoto und seine Klassenkameraden werden in eine Fantasiewelt versetzt, in der jeder einzigartige Fähigkeiten erhält. Hajime bekommt einen scheinbar nutzlosen Beruf als Handwerker, nutzt aber sein Wissen, um unglaubliche Technologien und Waffen zu erschaffen.",
    description_ja: "永本ハジメとクラスメートは、誰もがユニークな能力を得るファンタジーワールドに転移する。ハジメは一見役に立たない職人としての職業を得るが、自分の知識を利用して信じられないほどの技術や武器を作り出す。",
    description_zh: "永本肇和他的同学们被传送到了一个奇幻世界，每个人都获得了独特的能力。肇获得了一个看似无用的工匠职业，但他利用自己的知识创造了不可思议的技术和武器。",
    genres: ["Исекай", "Фэнтези", "Экшен", "Приключения"],
    genres_en: ["Isekai", "Fantasy", "Action", "Adventure"],
    genres_de: ["Isekai", "Fantasy", "Action", "Abenteuer"],
    genres_ja: ["異世界", "ファンタジー", "アクション", "アドベンチャー"],
    genres_zh: ["异世界", "奇幻", "动作", "冒险"],
    format: "TV Сериал",
    format_en: "TV Series",
    format_de: "TV-Serie",
    format_ja: "TVシリーズ",
    format_zh: "电视系列",
    episodes: 41,
    averageScore: 85
  },
  {
    id: 8,
    title: "Башня Бога",
    title_en: "Tower of God",
    title_de: "Turm Gottes",
    title_ja: "神之塔",
    title_zh: "神之塔",
    image: "https://v12.vost.pw/uploads/posts/2024-10/1727768359_1.jpg?v2",
    description: "Двадцать пятый Бам решает подняться на Таинственную Башню, чтобы найти свою подругу Рейчел. В башне его ждут смертельные испытания, политические интриги и встреча с необычными союзниками. Каждый этап башни — это новый мир с собственными правилами.",
    description_en: "Twenty-Fifth Bam decides to climb the Mysterious Tower to find his friend Rachel. In the tower, he faces deadly trials, political intrigues, and meets unusual allies. Each floor of the tower is a new world with its own rules.",
    description_de: "Der fünfundzwanzigste Bam beschließt, den Geheimnisvollen Turm zu besteigen, um seine Freundin Rachel zu finden. Im Turm erwartet ihn tödliche Prüfungen, politische Intrigen und die Begegnung mit ungewöhnlichen Verbündeten. Jede Etage des Turms ist eine neue Welt mit eigenen Regeln.",
    description_ja: "二十五夜は友人レイチェルを見つけるために神秘の塔に登ることを決意する。塔では、致命的な試練、政治的陰謀、そして異例の味方との出会いが待っている。塔の各階は独自のルールを持つ新しい世界だ。",
    description_zh: "第二十五夜决定攀登神秘之塔以寻找他的朋友蕾切尔。在塔中，他面临着致命的考验、政治阴谋，并遇到了不寻常的盟友。塔的每一层都是一个有着自己规则的新世界。",
    genres: ["Фэнтези", "Приключения", "Драма", "Экшен"],
    genres_en: ["Fantasy", "Adventure", "Drama", "Action"],
    genres_de: ["Fantasy", "Abenteuer", "Drama", "Action"],
    genres_ja: ["ファンタジー", "アドベンチャー", "ドラマ", "アクション"],
    genres_zh: ["奇幻", "冒险", "剧情", "动作"],
    format: "TV Сериал",
    format_en: "TV Series",
    format_de: "TV-Serie",
    format_ja: "TVシリーズ",
    format_zh: "电视系列",
    episodes: 39,
    averageScore: 87
  },
  {
    id: 9,
    title: "Почему все забыли мой мир?",
    title_en: "Why Did Everyone Forget My World?",
    title_de: "Warum hat jeder meine Welt vergessen?",
    title_ja: "なぜ誰もが私の世界を忘れたのか？",
    title_zh: "为什么大家都忘了我的世界？",
    image: "https://v12.vost.pw/uploads/posts/2024-07/1720887961_1.jpg?v2",
    description: "Главный герой просыпается в мире, где никто не помнит его существования. Постепенно он обнаруживает, что стал невидимкой для общества, и начинает расследование таинственного явления, пытаясь вернуть свое место в мире.",
    description_en: "The protagonist wakes up in a world where no one remembers his existence. Gradually, he discovers that he has become invisible to society and begins investigating the mysterious phenomenon, trying to regain his place in the world.",
    description_de: "Der Protagonist erwacht in einer Welt, in der sich niemand an seine Existenz erinnert. Allmählich entdeckt er, dass er für die Gesellschaft unsichtbar geworden ist, und beginnt mit der Untersuchung des mysteriösen Phänomens, um seinen Platz in der Welt zurückzuerlangen.",
    description_ja: "主人公は、誰も彼の存在を覚えていない世界に目を覚ます。次第に、彼は社会から見えなくなったことを発見し、神秘的な現象の調査を始め、世界での自分の場所を取り戻そうとする。",
    description_zh: "主角在一个没有人记得他存在的世界中醒来。逐渐地，他发现自己在社会中变得隐形，并开始调查这个神秘现象，试图重新获得他在世界中的位置。",
    genres: ["Драма", "Мистика", "Психологическое", "Фэнтези"],
    genres_en: ["Drama", "Mystery", "Psychological", "Fantasy"],
    genres_de: ["Drama", "Mystery", "Psychologisch", "Fantasy"],
    genres_ja: ["ドラマ", "ミステリー", "心理", "ファンタジー"],
    genres_zh: ["剧情", "悬疑", "心理", "奇幻"],
    format: "TV Сериал",
    format_en: "TV Series",
    format_de: "TV-Serie",
    format_ja: "TVシリーズ",
    format_zh: "电视系列",
    episodes: 12,
    averageScore: 82
  },
  {
    id: 10,
    title: "О моём перерождении в слизь",
    title_en: "That Time I Got Reincarnated as a Slime",
    title_de: "Als ich als Schleim wiedergeboren wurde",
    title_ja: "転生したらスライムだった件",
    title_zh: "关于我转生变成史莱姆这档事",
    image: "https://v12.vost.pw/uploads/posts/2024-03/1710334118_1.jpg?v2",
    description: "Сатору Миками, обычный офисный работник, перерождается в фэнтезийном мире в виде слайма. Обладая уникальными способностями поглощения и имитации, он начинает строить собственное королевство, объединяя различные расы и создавая утопическое общество.",
    description_en: "Satoru Mikami, an ordinary office worker, is reincarnated in a fantasy world as a slime. Possessing unique absorption and imitation abilities, he begins to build his own kingdom, uniting various races and creating a utopian society.",
    description_de: "Satoru Mikami, ein gewöhnlicher Büroangestellter, wird in einer Fantasiewelt als Schleim wiedergeboren. Mit einzigartigen Absorptions- und Imitationsfähigkeiten beginnt er, sein eigenes Königreich aufzubauen, verschiedene Rassen zu vereinen und eine utopische Gesellschaft zu schaffen.",
    description_ja: "普通の会社員である三上悟は、ファンタジーワールドでスライムとして転生する。独自の吸収と模倣能力を備え、さまざまな種族を統合し、ユートピア社会を作りながら、自分の王国を築き始める。",
    description_zh: "普通的上班族三上悟在奇幻世界转生为史莱姆。拥有独特的吸收和模仿能力，他开始建立自己的王国，团结各个种族，创建一个乌托邦社会。",
    genres: ["Исекай", "Фэнтези", "Комедия", "Приключения"],
    genres_en: ["Isekai", "Fantasy", "Comedy", "Adventure"],
    genres_de: ["Isekai", "Fantasy", "Komödie", "Abenteuer"],
    genres_ja: ["異世界", "ファンタジー", "コメディ", "アドベンチャー"],
    genres_zh: ["异世界", "奇幻", "喜剧", "冒险"],
    format: "TV Сериал",
    format_en: "TV Series",
    format_de: "TV-Serie",
    format_ja: "TVシリーズ",
    format_zh: "电视系列",
    episodes: 84,
    averageScore: 89
  }

];
